version: "3.9"

services:
  app:
    build:
      context: .
      args:
      - DEV=true
    ports:
    # map port 8000 on local machine to port 8000 inside our container
    - "8000:8000"
    volumes:
    # map directories from our local directory into docker container
    # this way we can refrect our local changes to the container
    - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"